### PR TITLE
Ocean tutorial: set ngkpt the same as nkpt

### PR DESCRIPTION
**Pull request by deyulu**

### CODE REVIEW

**Comment by matthewcarbone** [comment]
@FCMeng Yeah not exactly sure what's going on with that. If you have any ideas let me know, but it's not your code or the branch that's causing the issue.

**Comment by deyulu** [comment]
@matthewcarbone @FCMeng We need to solve this issue before the workshop, as the current nkpt setting is incorrect.

**Comment by matthewcarbone** [comment]
Truely nonsensical. Codecov was removed from PyPi (see e.g. [here](https://github.com/home-assistant/core/issues/91283) for some more discussion). It's now fixed on `master`. Just rebase this branch and it'll fix the tests.

**Comment by deyulu** [comment]
@matthewcarbone Thank you. I rebased the branch and most of the tests passed with one still running. It looks like I also need to add the ocean tutorial notebook.

**Comment by deyulu** [comment]
Does anybody know why [Run unit testing suite (macOS-latest, 3.11)] takes so long? It has run 1.5 hours and still not finished.

**Comment by FCMeng** [comment]
It is done on my side.

**Comment by matthewcarbone** [comment]
> Does anybody know why [Run unit testing suite (macOS-latest, 3.11)] takes so long? It has run 1.5 hours and still not finished.

@FCMeng it's showing successful in 3 minutes. Maybe a glitch on your end?

**Comment by matthewcarbone** [comment]
@deyulu can you add the changes from your Ocean notebook to the only one in `master` right now? I combined them before.

**Comment by deyulu** [comment]
@matthewcarbone Changes in k-mesh doesn't affect the notebook. No change to be added. I didn't notice that you already combined them. However, I need to add "import lightshow" for the notebook to work.

**Comment by matthewcarbone** [comment]
@deyulu No problem, and I see you removed the notebook I was referring to. Now there's only a single change as expected. Rebasing!

**Pull request merged**
